### ISSUE TITLE
Payola::Sale requires Affiliate and Coupon in Rails 5

### ISSUE THREAD

**Issue by dtredger** [payolapayments/payola#259]
Because belongs_to associations are required by default in Rails 5, Sales are invalid without an Affiliate and Coupon. This arose for me in the context of a subscription, which creates sales from Stripe webhooks through Payola::InvoicePaid. 

Apologies if there's a reason Affiliate and Coupon should be required, and thanks for the fantastic gem.

**Comment by peterkeen** [comment]
Thanks @dtredger. Looks like we just have to set `optional: true` on the associations.

http://blog.bigbinary.com/2016/02/15/rails-5-makes-belong-to-association-required-by-default.html

**Comment by eliotsykes** [comment]
IIRC the dummy app has a temporary workaround for when the test suite runs to avoid this issue, by commenting out the `belongs_to_required_by_default` option in the Rails5-only `new_framework_defaults.rb` initializer:

```diff
  # Require `belongs_to` associations by default. Previous versions had false.
  # Rails.application.config.active_record.belongs_to_required_by_default = true
```
Source: https://github.com/peterkeen/payola/blob/2cbecc0e853504c233e633311e375497b6f2bbf3/spec/dummy/config/initializers/new_framework_defaults.rb#L18-L19

When the fix for this issue is done on the Payola models to set `optional: true` on the `belongs_to` associations, its probably a good idea to also set `belongs_to_required_by_default` to `true`:

```diff
  # Require `belongs_to` associations by default. Previous versions had false.
-  # Rails.application.config.active_record.belongs_to_required_by_default = true
+  Rails.application.config.active_record.belongs_to_required_by_default = true
```
(In the meantime developers encountering this issue in Rails 5 apps can set `belongs_to_required_default` to `false` in the initializer).

**Comment by jscho13** [comment]
I was experiencing the following error message when attempting to test payola payments:
`This seems to be taking too long. Please contact support and give them transaction ID: jfhtsr`

As eliotskyes mentioned adding the line `Rails.application.config.active_record.belongs_to_required_by_default = true` in your `application.rb` will do the trick.
