### ISSUE TITLE
Question: How do we know this is the card that was used?

### ISSUE THREAD

**Issue by MarkMurphy** [payolapayments/payola#273]
The `StartSubscription` service uses `customer.sources.data.first` as the card that supposedly purchased the subscription. Isn't this code making an assumption?

What happens if the customer (who previously existed) has multiple cards?

**Comment by caleuanhopkins** [comment]
[https://stripe.com/docs/api#customer_object](https://stripe.com/docs/api#customer_object)

Stripe uses the `default_source` object to attached the primary card to the customer's `source` object, therefore making it the first `source` when you call the `customer` object.

As for if it is the card that was used to pay for a subscription, Stripe will charge the card that is set as the primary card in the customer's information. Each subscription is paid off as an Invoice using the primary card attached to the customer **at the point the subscription is due to be paid**. Each invoice has a `charge` object and each `charge` object has a `source` object. You can use that relation structure to trace back which card was used to pay the subscription. 

So if the Customer would have to use an interface to change their primary card, and therefore use another card for paying the subscription.

Is your question about which card should be charged per subscription charge or how to see which card is was used to pay for the subscription previously?

**Comment by MarkMurphy** [comment]
I guess I was more or less just making an observation about the `StartSubscription` service. We've built our own API and UI such that a customer is able to add, remove and update their cards including change their default card. So with that in mind, `customer.sources.data.first` is probably not the best choice if we're trying to store the card type and expiry related to the subscription.

**Comment by caleuanhopkins** [comment]
I've built the same sort of thing. Although, looking at the `StartSubscription` class, I'm not convinced that the `customer.sources.data.first` method is designed to get the card data for a subscription. It'll get the current primary card but it looks like it's  designed to do that for charging a customer using said card.

Sounds like your on the right track anyway. For anyone arriving here in the future, I'd advise that `customer.sources.data.first` should only be used for getting the customers current primary card, not for getting data on which cards previous invoices have been paid with.
